import { useState } from 'react';
import {
  Plus, Calendar, MapPin, Clock, Users, ChevronRight,
  ChevronLeft, Edit3, Trash2, Send, Eye, EyeOff, Star,
  Trophy, PartyPopper, Camera, Utensils, X, Check,
  Truck, User, MessageSquare, Award, TrendingUp,
  ChevronDown, ChevronUp, AlertCircle
} from 'lucide-react';

export default function Events() {
  const [activeTab, setActiveTab] = useState('events');
  const [selectedMonth, setSelectedMonth] = useState(new Date(2025, 1, 1)); // February 2025
  const [showAddEventModal, setShowAddEventModal] = useState(false);
  const [selectedEvent, setSelectedEvent] = useState(null);
  const [selectedRace, setSelectedRace] = useState(null);
  const [raceFilter, setRaceFilter] = useState('upcoming');
  const [expandedRaces, setExpandedRaces] = useState([1, 2]);

  // Grooms list
  const grooms = [
    { id: 1, name: 'Emma Larsson' },
    { id: 2, name: 'Johan Karlsson' },
    { id: 3, name: 'Lisa Andersson' },
    { id: 4, name: 'Marcus Berg' },
  ];

  // Transport drivers
  const transportDrivers = [
    { id: 1, name: 'Peter Holm' },
    { id: 2, name: 'Anders Nilsson' },
    { id: 3, name: 'Markus Svedberg' },
  ];

  // Owner events - mix of manual and auto-generated from race entries
  // These match the events shown in the horse owner app
  const [ownerEvents, setOwnerEvents] = useState([
    {
      id: 1,
      title: 'Hästägarfest 2025',
      type: 'party',
      date: new Date(2025, 2, 22),
      time: '18:00',
      location: 'Täby Galopp, Festsalen',
      description: 'Välkommen till årets stora hästägarfest! En kväll för att fira säsongen tillsammans med alla delägare i stallet.\n\nProgram:\n18:00 - Välkomstdrink\n18:30 - Mingel och visning av stallets hästar\n19:30 - Trerätters middag\n21:00 - Prisutdelning: Årets häst & Årets ägare\n22:00 - Liveband & dans\n\nKlädkod: Mörk kostym / festlig klänning\n\nAnmäl er senast 15 mars. Meddela eventuella allergier vid anmälan.',
      image: null,
      isAutoGenerated: false,
      publishedToApp: true,
      attendees: 34,
      maxAttendees: 80,
      rsvpDeadline: new Date(2025, 2, 15),
      relatedHorses: [],
      createdBy: 'Markus Svedberg'
    },
    {
      id: 2,
      title: 'V75 Solvalla - Tävlingsdag',
      type: 'race-day',
      date: new Date(2025, 1, 15),
      time: '14:00',
      location: 'Solvalla',
      description: 'Stor V75-lördag på Solvalla! Deeply Express ställer upp i V75-4 (lopp 4) och Mansa Musa Mearas går i V75-7 (lopp 7).\n\nDeply Express startar från spår 3 över 2140 meter med Örjan Kihlström i sulkyn. Mansa Musa Mearas har fått spår 8 över 2140 meter med Johan Untersteiner.\n\nVälkommen att heja på era hästar! Vi samlas i ägarloungen 30 minuter före första starten.',
      trainerNotes: 'Deeply Express har tränat fantastiskt den senaste veckan och känns i toppform. Han joggar på ca 1.14-tempo och verkar riktigt taggad. Bra utgångsläge från spår 3.\n\nMansa Musa Mearas har fått vila efter senast och är pigg och fräsch. Spår 8 är inte optimalt men Johan brukar lösa det bra. Vi siktar på topp 3 för båda!',
      image: null,
      isAutoGenerated: true,
      publishedToApp: true,
      attendees: 18,
      maxAttendees: null,
      rsvpDeadline: null,
      relatedHorses: ['Deeply Express', 'Mansa Musa Mearas'],
      relatedRaceId: 1,
      createdBy: 'System'
    },
    {
      id: 3,
      title: 'Stallvisning & Fika',
      type: 'stable-visit',
      date: new Date(2025, 1, 22),
      time: '10:00',
      location: 'Stall Markus Svedberg, Täby',
      description: 'Öppen stallvisning för alla hästägare. Träffa era hästar, prata med skötarna och njut av fika. Vi går igenom träningsplaner och kommande starter.',
      image: null,
      isAutoGenerated: false,
      publishedToApp: true,
      attendees: 18,
      maxAttendees: 30,
      rsvpDeadline: new Date(2025, 1, 20),
      relatedHorses: [],
      createdBy: 'Markus Svedberg'
    },
    {
      id: 4,
      title: 'V86 Åby - Tävlingsdag',
      type: 'race-day',
      date: new Date(2025, 1, 16),
      time: '18:30',
      location: 'Åby',
      description: 'Kvällstävlingar på Åby med V86! Pargas Sox går i V86-2 (lopp 2) och Optimum Volante startar i lopp 5.\n\nPargas Sox har perfekt läge från spår 1 över 1640 meter - voltstart. Optimum Volante prövas på längre distans, 2140 meter från spår 6.',
      trainerNotes: 'Pargas Sox är i finfin form och från spår 1 i volt är det bara att köra! Känns som en riktig vinstchans.\n\nOptimum Volante testas på längre distans för första gången. Vi vet inte exakt hur han klarar det men han har visat bra kapacitet på träning.',
      image: null,
      isAutoGenerated: true,
      publishedToApp: true,
      attendees: 8,
      maxAttendees: null,
      rsvpDeadline: null,
      relatedHorses: ['Optimum Volante', 'Pargas Sox'],
      relatedRaceId: 2,
      createdBy: 'System'
    },
    {
      id: 5,
      title: 'Ägarträff Solvalla',
      type: 'meetup',
      date: new Date(2025, 2, 8),
      time: '12:00',
      location: 'Solvalla, VIP-loungen',
      description: 'Lunch och mingel för alla hästägare i samband med V75-tävlingarna. Markus går igenom läget i stallet och vi diskuterar kommande planer för våra hästar.\n\nLunch serveras kl 12:30. Efteråt tittar vi tillsammans på loppen.',
      image: null,
      isAutoGenerated: false,
      publishedToApp: true,
      attendees: 22,
      maxAttendees: 40,
      rsvpDeadline: new Date(2025, 2, 5),
      relatedHorses: [],
      createdBy: 'Markus Svedberg'
    },
    {
      id: 6,
      title: 'V64 Mantorp - Tävlingsdag',
      type: 'race-day',
      date: new Date(2025, 1, 18),
      time: '19:00',
      location: 'Mantorp',
      description: 'Charente Bro gör årets första start på Mantorp! Han går i V64-3 (lopp 3) över 2140 meter från spår 5.',
      trainerNotes: 'Charente har vintrat fint och känns redo för säsongspremiär. Vi tar det försiktigt i första starten men han har tränat bra och ska vara med i matchen.',
      image: null,
      isAutoGenerated: true,
      publishedToApp: true,
      attendees: 4,
      maxAttendees: null,
      rsvpDeadline: null,
      relatedHorses: ['Charente Bro'],
      relatedRaceId: 3,
      createdBy: 'System'
    }
  ]);

  // Race calendar data - upcoming races
  const [races, setRaces] = useState([
    {
      id: 1,
      date: new Date(2025, 1, 15),
      track: 'Solvalla',
      raceType: 'V75',
      status: 'upcoming',
      departureTime: '11:30',
      transportDriver: 'Peter Holm',
      entries: [
        {
          horse: 'Deeply Express',
          race: 4,
          poolRace: 'V75-4',
          startNumber: 3,
          driver: 'Örjan Kihlström',
          distance: '2140m',
          groom: 'Emma Larsson',
          status: 'confirmed',
          placement: null,
          earnings: null
        },
        {
          horse: 'Mansa Musa Mearas',
          race: 7,
          poolRace: 'V75-7',
          startNumber: 8,
          driver: 'Johan Untersteiner',
          distance: '2140m',
          groom: 'Johan Karlsson',
          status: 'confirmed',
          placement: null,
          earnings: null
        }
      ]
    },
    {
      id: 2,
      date: new Date(2025, 1, 16),
      track: 'Åby',
      raceType: 'V86',
      status: 'upcoming',
      departureTime: '14:00',
      transportDriver: 'Anders Nilsson',
      entries: [
        {
          horse: 'Pargas Sox',
          race: 2,
          poolRace: 'V86-2',
          startNumber: 1,
          driver: 'Markus Svedberg',
          distance: '1640m',
          groom: 'Lisa Andersson',
          status: 'confirmed',
          placement: null,
          earnings: null
        },
        {
          horse: 'Optimum Volante',
          race: 5,
          poolRace: null,
          startNumber: 6,
          driver: 'Markus Svedberg',
          distance: '2140m',
          groom: 'Marcus Berg',
          status: 'confirmed',
          placement: null,
          earnings: null
        }
      ]
    },
    {
      id: 3,
      date: new Date(2025, 1, 18),
      track: 'Mantorp',
      raceType: 'V64',
      status: 'upcoming',
      departureTime: '15:00',
      transportDriver: 'Markus Svedberg',
      entries: [
        {
          horse: 'Charente Bro',
          race: 3,
          poolRace: 'V64-3',
          startNumber: 5,
          driver: 'Markus Svedberg',
          distance: '2140m',
          groom: 'Emma Larsson',
          status: 'confirmed',
          placement: null,
          earnings: null
        }
      ]
    },
    {
      id: 4,
      date: new Date(2025, 1, 22),
      track: 'Solvalla',
      raceType: 'V75',
      status: 'upcoming',
      departureTime: '11:00',
      transportDriver: 'Peter Holm',
      entries: [
        {
          horse: 'Global Harmony',
          race: 2,
          poolRace: 'V75-2',
          startNumber: 4,
          driver: 'Örjan Kihlström',
          distance: '2140m',
          groom: 'Johan Karlsson',
          status: 'pending',
          placement: null,
          earnings: null
        },
        {
          horse: 'Deeply Express',
          race: 6,
          poolRace: 'V75-6',
          startNumber: 7,
          driver: 'Örjan Kihlström',
          distance: '2640m',
          groom: 'Emma Larsson',
          status: 'pending',
          placement: null,
          earnings: null
        }
      ]
    },
    {
      id: 5,
      date: new Date(2025, 1, 23),
      track: 'Åby',
      raceType: 'Lunch',
      status: 'upcoming',
      departureTime: '08:30',
      transportDriver: 'Anders Nilsson',
      entries: [
        {
          horse: 'Miami Mearas',
          race: 4,
          poolRace: null,
          startNumber: 2,
          driver: 'Markus Svedberg',
          distance: '2140m',
          groom: 'Lisa Andersson',
          status: 'pending',
          placement: null,
          earnings: null
        }
      ]
    },
    // Completed races
    {
      id: 101,
      date: new Date(2025, 1, 8),
      track: 'Solvalla',
      raceType: 'V75',
      status: 'completed',
      departureTime: '11:00',
      transportDriver: 'Peter Holm',
      entries: [
        {
          horse: 'Deeply Express',
          race: 5,
          poolRace: 'V75-5',
          startNumber: 2,
          driver: 'Örjan Kihlström',
          distance: '2140m',
          groom: 'Emma Larsson',
          status: 'completed',
          placement: 1,
          earnings: 150000
        },
        {
          horse: 'Global Harmony',
          race: 3,
          poolRace: 'V75-3',
          startNumber: 6,
          driver: 'Johan Untersteiner',
          distance: '2140m',
          groom: 'Johan Karlsson',
          status: 'completed',
          placement: 4,
          earnings: 20000
        }
      ]
    },
    {
      id: 102,
      date: new Date(2025, 1, 2),
      track: 'Åby',
      raceType: 'V86',
      status: 'completed',
      departureTime: '14:00',
      transportDriver: 'Anders Nilsson',
      entries: [
        {
          horse: 'Pargas Sox',
          race: 4,
          poolRace: 'V86-4',
          startNumber: 3,
          driver: 'Markus Svedberg',
          distance: '2140m',
          groom: 'Lisa Andersson',
          status: 'completed',
          placement: 2,
          earnings: 75000
        }
      ]
    },
    {
      id: 103,
      date: new Date(2025, 0, 25),
      track: 'Jägersro',
      raceType: 'V64',
      status: 'completed',
      departureTime: '15:30',
      transportDriver: 'Markus Svedberg',
      entries: [
        {
          horse: 'Grazzhopper',
          race: 6,
          poolRace: 'V64-6',
          startNumber: 1,
          driver: 'Örjan Kihlström',
          distance: '2640m',
          groom: 'Marcus Berg',
          status: 'completed',
          placement: 1,
          earnings: 100000
        },
        {
          horse: 'Caspian Bro',
          race: 2,
          poolRace: null,
          startNumber: 8,
          driver: 'Markus Svedberg',
          distance: '2140m',
          groom: 'Emma Larsson',
          status: 'completed',
          placement: 6,
          earnings: 5000
        }
      ]
    }
  ]);

  // New event form
  const [newEvent, setNewEvent] = useState({
    title: '',
    type: 'meetup',
    date: '',
    time: '',
    location: '',
    description: '',
    maxAttendees: '',
    rsvpDeadline: '',
    publishedToApp: false
  });

  const eventTypes = [
    { id: 'meetup', label: 'Träff', icon: Users, color: '#4F7CFF' },
    { id: 'party', label: 'Fest', icon: PartyPopper, color: '#8B5CF6' },
    { id: 'stable-visit', label: 'Stallvisning', icon: Camera, color: '#22C55E' },
    { id: 'dinner', label: 'Middag', icon: Utensils, color: '#F59E0B' },
    { id: 'race-day', label: 'Tävlingsdag', icon: Trophy, color: '#EF4444' }
  ];

  const getEventTypeInfo = (type) => {
    return eventTypes.find(t => t.id === type) || eventTypes[0];
  };

  const formatDate = (date) => {
    return date.toLocaleDateString('sv-SE', { weekday: 'short', day: 'numeric', month: 'short' });
  };

  const formatDateLong = (date) => {
    return date.toLocaleDateString('sv-SE', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' });
  };

  const isToday = (date) => {
    const today = new Date();
    return date.toDateString() === today.toDateString();
  };

  const isPast = (date) => {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    return date < today;
  };

  const isSameMonth = (date1, date2) => {
    return date1.getMonth() === date2.getMonth() && date1.getFullYear() === date2.getFullYear();
  };

  const navigateMonth = (direction) => {
    const newMonth = new Date(selectedMonth);
    newMonth.setMonth(newMonth.getMonth() + direction);
    setSelectedMonth(newMonth);
  };

  const formatCurrency = (amount) => {
    return new Intl.NumberFormat('sv-SE', { style: 'currency', currency: 'SEK', maximumFractionDigits: 0 }).format(amount);
  };

  const getPlacementColor = (placement) => {
    if (placement === 1) return '#FFD700';
    if (placement === 2) return '#C0C0C0';
    if (placement === 3) return '#CD7F32';
    return 'var(--text-muted)';
  };

  const getPlacementLabel = (placement) => {
    if (!placement) return '-';
    if (placement === 1) return '1:a';
    if (placement === 2) return '2:a';
    if (placement === 3) return '3:a';
    return `${placement}:a`;
  };

  // Filter events by current month
  const filteredEvents = ownerEvents.filter(event => isSameMonth(event.date, selectedMonth));

  // Filter races
  const upcomingRaces = races.filter(race => race.status === 'upcoming').sort((a, b) => a.date - b.date);
  const completedRaces = races.filter(race => race.status === 'completed').sort((a, b) => b.date - a.date);

  const filteredRaces = raceFilter === 'upcoming' ? upcomingRaces : completedRaces;

  const toggleRaceExpanded = (raceId) => {
    setExpandedRaces(prev =>
      prev.includes(raceId)
        ? prev.filter(id => id !== raceId)
        : [...prev, raceId]
    );
  };

  const handleCreateEvent = () => {
    const event = {
      id: Date.now(),
      title: newEvent.title,
      type: newEvent.type,
      date: new Date(newEvent.date),
      time: newEvent.time,
      location: newEvent.location,
      description: newEvent.description,
      image: null,
      isAutoGenerated: false,
      publishedToApp: newEvent.publishedToApp,
      attendees: 0,
      maxAttendees: newEvent.maxAttendees ? parseInt(newEvent.maxAttendees) : null,
      rsvpDeadline: newEvent.rsvpDeadline ? new Date(newEvent.rsvpDeadline) : null,
      relatedHorses: [],
      createdBy: 'Markus Svedberg'
    };

    setOwnerEvents(prev => [...prev, event]);
    setShowAddEventModal(false);
    setNewEvent({
      title: '',
      type: 'meetup',
      date: '',
      time: '',
      location: '',
      description: '',
      maxAttendees: '',
      rsvpDeadline: '',
      publishedToApp: false
    });
  };

  const togglePublishEvent = (eventId) => {
    setOwnerEvents(prev => prev.map(event =>
      event.id === eventId
        ? { ...event, publishedToApp: !event.publishedToApp }
        : event
    ));
  };

  const deleteEvent = (eventId) => {
    setOwnerEvents(prev => prev.filter(event => event.id !== eventId));
    setSelectedEvent(null);
  };

  const updateRaceEntry = (raceId, horseIndex, field, value) => {
    setRaces(prev => prev.map(race => {
      if (race.id === raceId) {
        const newEntries = [...race.entries];
        newEntries[horseIndex] = { ...newEntries[horseIndex], [field]: value };
        return { ...race, entries: newEntries };
      }
      return race;
    }));
  };

  const updateRace = (raceId, field, value) => {
    setRaces(prev => prev.map(race =>
      race.id === raceId ? { ...race, [field]: value } : race
    ));
  };

  // Stats
  const upcomingEventsCount = ownerEvents.filter(e => !isPast(e.date)).length;
  const publishedEventsCount = ownerEvents.filter(e => e.publishedToApp && !isPast(e.date)).length;
  const upcomingStartsCount = upcomingRaces.reduce((sum, r) => sum + r.entries.length, 0);
  const totalEarningsThisMonth = completedRaces
    .filter(r => isSameMonth(r.date, new Date()))
    .reduce((sum, r) => sum + r.entries.reduce((s, e) => s + (e.earnings || 0), 0), 0);

  return (
    <div className="page-content">
      <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
        <div>
          <h1>Lopp & Event</h1>
          <p>Hantera event för hästägare och följ tävlingskalendern</p>
        </div>
        {activeTab === 'events' && (
          <button className="btn btn-primary" onClick={() => setShowAddEventModal(true)}>
            <Plus size={18} />
            Nytt event
          </button>
        )}
      </div>

      {/* Tabs */}
      <div style={{
        display: 'flex',
        gap: '8px',
        marginBottom: '24px',
        borderBottom: '1px solid var(--border)',
        paddingBottom: '0'
      }}>
        <button
          onClick={() => setActiveTab('events')}
          style={{
            padding: '12px 24px',
            background: 'none',
            border: 'none',
            borderBottom: activeTab === 'events' ? '2px solid var(--primary)' : '2px solid transparent',
            color: activeTab === 'events' ? 'var(--primary)' : 'var(--text-secondary)',
            fontWeight: activeTab === 'events' ? '600' : '400',
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            gap: '8px'
          }}
        >
          <PartyPopper size={18} />
          Ägarevents
        </button>
        <button
          onClick={() => setActiveTab('races')}
          style={{
            padding: '12px 24px',
            background: 'none',
            border: 'none',
            borderBottom: activeTab === 'races' ? '2px solid var(--primary)' : '2px solid transparent',
            color: activeTab === 'races' ? 'var(--primary)' : 'var(--text-secondary)',
            fontWeight: activeTab === 'races' ? '600' : '400',
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            gap: '8px'
          }}
        >
          <Trophy size={18} />
          Tävlingskalender
        </button>
      </div>

      {/* EVENTS TAB */}
      {activeTab === 'events' && (
        <>
          {/* Quick Stats */}
          <div className="stats-grid" style={{ gridTemplateColumns: 'repeat(4, 1fr)', marginBottom: '24px' }}>
            <div className="stat-card">
              <div className="stat-card-label">Kommande event</div>
              <div className="stat-card-value">{upcomingEventsCount}</div>
              <div className="stat-card-sub">planerade</div>
            </div>
            <div className="stat-card">
              <div className="stat-card-label">Publicerade</div>
              <div className="stat-card-value">{publishedEventsCount}</div>
              <div className="stat-card-sub">synliga i appen</div>
            </div>
            <div className="stat-card">
              <div className="stat-card-label">Kommande starter</div>
              <div className="stat-card-value">{upcomingStartsCount}</div>
              <div className="stat-card-sub">anmälda</div>
            </div>
            <div className="stat-card">
              <div className="stat-card-label">Intjänat denna månad</div>
              <div className="stat-card-value" style={{ fontSize: '22px' }}>{formatCurrency(totalEarningsThisMonth)}</div>
              <div className="stat-card-sub">i prispengar</div>
            </div>
          </div>

          {/* App Preview Info */}
          <div className="card" style={{ marginBottom: '24px', background: 'linear-gradient(135deg, #4F7CFF08 0%, #8B5CF608 100%)' }}>
            <div style={{ padding: '20px', display: 'flex', alignItems: 'center', gap: '16px' }}>
              <div style={{
                width: '48px',
                height: '48px',
                borderRadius: '12px',
                background: 'var(--primary)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center'
              }}>
                <Eye size={24} style={{ color: 'white' }} />
              </div>
              <div style={{ flex: 1 }}>
                <h3 style={{ marginBottom: '4px' }}>Ägarappen</h3>
                <p style={{ fontSize: '14px', color: 'var(--text-muted)', margin: 0 }}>
                  Publicerade event och tävlingsdagar visas automatiskt i hästägarnas app.
                  Tävlingsdagar skapas automatiskt när hästar anmäls och du kan lägga till exklusiv info.
                </p>
              </div>
            </div>
          </div>

          {/* Month Navigation */}
          <div className="card" style={{ marginBottom: '24px' }}>
            <div style={{ padding: '16px 20px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
                <button className="btn btn-secondary" style={{ padding: '8px' }} onClick={() => navigateMonth(-1)}>
                  <ChevronLeft size={20} />
                </button>
                <h3 style={{ minWidth: '200px', textAlign: 'center', textTransform: 'capitalize' }}>
                  {selectedMonth.toLocaleDateString('sv-SE', { month: 'long', year: 'numeric' })}
                </h3>
                <button className="btn btn-secondary" style={{ padding: '8px' }} onClick={() => navigateMonth(1)}>
                  <ChevronRight size={20} />
                </button>
                <button
                  className="btn btn-secondary"
                  onClick={() => setSelectedMonth(new Date())}
                  style={{ marginLeft: '8px' }}
                >
                  Denna månad
                </button>
              </div>
              <div style={{ display: 'flex', gap: '12px' }}>
                {eventTypes.map(type => (
                  <div
                    key={type.id}
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: '6px',
                      fontSize: '12px',
                      color: 'var(--text-muted)'
                    }}
                  >
                    <div style={{
                      width: '10px',
                      height: '10px',
                      borderRadius: '3px',
                      background: type.color
                    }} />
                    {type.label}
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Events List */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            {filteredEvents.length === 0 ? (
              <div className="card" style={{ padding: '60px 40px', textAlign: 'center' }}>
                <Calendar size={48} style={{ marginBottom: '16px', opacity: 0.3, color: 'var(--text-muted)' }} />
                <h3 style={{ color: 'var(--text-muted)', marginBottom: '8px' }}>Inga event denna månad</h3>
                <p style={{ color: 'var(--text-muted)', fontSize: '14px' }}>Skapa ett nytt event eller bläddra till en annan månad</p>
              </div>
            ) : (
              filteredEvents
                .sort((a, b) => a.date - b.date)
                .map(event => {
                  const typeInfo = getEventTypeInfo(event.type);
                  const TypeIcon = typeInfo.icon;

                  return (
                    <div
                      key={event.id}
                      className="card"
                      style={{
                        borderLeft: `4px solid ${typeInfo.color}`,
                        opacity: isPast(event.date) ? 0.6 : 1,
                        cursor: 'pointer'
                      }}
                      onClick={() => setSelectedEvent(event)}
                    >
                      <div style={{ padding: '16px 20px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
                          <div style={{
                            width: '56px',
                            height: '56px',
                            borderRadius: '12px',
                            background: `${typeInfo.color}15`,
                            display: 'flex',
                            flexDirection: 'column',
                            alignItems: 'center',
                            justifyContent: 'center',
                            color: typeInfo.color
                          }}>
                            <div style={{ fontSize: '18px', fontWeight: '700', lineHeight: 1 }}>
                              {event.date.getDate()}
                            </div>
                            <div style={{ fontSize: '10px', textTransform: 'uppercase' }}>
                              {event.date.toLocaleDateString('sv-SE', { month: 'short' })}
                            </div>
                          </div>
                          <div>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
                              <h3 style={{ fontSize: '16px', fontWeight: '600' }}>{event.title}</h3>
                              {event.isAutoGenerated && (
                                <span style={{
                                  fontSize: '10px',
                                  background: '#EF444415',
                                  color: '#EF4444',
                                  padding: '2px 8px',
                                  borderRadius: '4px',
                                  fontWeight: '500'
                                }}>
                                  Från anmälan
                                </span>
                              )}
                              {event.publishedToApp ? (
                                <span style={{ display: 'flex', alignItems: 'center', gap: '4px', fontSize: '11px', color: 'var(--success)' }}>
                                  <Eye size={12} />
                                  I appen
                                </span>
                              ) : (
                                <span style={{ display: 'flex', alignItems: 'center', gap: '4px', fontSize: '11px', color: 'var(--text-muted)' }}>
                                  <EyeOff size={12} />
                                  Utkast
                                </span>
                              )}
                            </div>
                            <div style={{ fontSize: '13px', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: '12px' }}>
                              <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                                <Clock size={12} />
                                {event.time}
                              </span>
                              <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                                <MapPin size={12} />
                                {event.location}
                              </span>
                              {event.maxAttendees && (
                                <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                                  <Users size={12} />
                                  {event.attendees}/{event.maxAttendees}
                                </span>
                              )}
                            </div>
                            {event.relatedHorses.length > 0 && (
                              <div style={{ marginTop: '8px', display: 'flex', gap: '6px' }}>
                                {event.relatedHorses.map(horse => (
                                  <span
                                    key={horse}
                                    style={{
                                      fontSize: '11px',
                                      background: `${typeInfo.color}15`,
                                      color: typeInfo.color,
                                      padding: '2px 8px',
                                      borderRadius: '4px',
                                      fontWeight: '500'
                                    }}
                                  >
                                    {horse}
                                  </span>
                                ))}
                              </div>
                            )}
                          </div>
                        </div>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                          <button
                            className="btn btn-secondary"
                            style={{ padding: '8px' }}
                            onClick={(e) => {
                              e.stopPropagation();
                              togglePublishEvent(event.id);
                            }}
                            title={event.publishedToApp ? 'Avpublicera' : 'Publicera'}
                          >
                            {event.publishedToApp ? <EyeOff size={16} /> : <Eye size={16} />}
                          </button>
                          <ChevronRight size={20} style={{ color: 'var(--text-muted)' }} />
                        </div>
                      </div>
                    </div>
                  );
                })
            )}
          </div>
        </>
      )}

      {/* RACES TAB */}
      {activeTab === 'races' && (
        <>
          {/* Filter Tabs */}
          <div style={{ display: 'flex', gap: '0', marginBottom: '24px' }}>
            <button
              onClick={() => setRaceFilter('upcoming')}
              style={{
                padding: '12px 24px',
                background: raceFilter === 'upcoming' ? 'var(--primary)' : 'white',
                color: raceFilter === 'upcoming' ? 'white' : 'var(--text-secondary)',
                border: '1px solid var(--border)',
                borderRadius: '8px 0 0 8px',
                cursor: 'pointer',
                fontWeight: raceFilter === 'upcoming' ? '600' : '400',
                display: 'flex',
                alignItems: 'center',
                gap: '8px'
              }}
            >
              <Calendar size={16} />
              Kommande
              <span style={{
                background: raceFilter === 'upcoming' ? 'rgba(255,255,255,0.2)' : 'var(--background)',
                padding: '2px 8px',
                borderRadius: '10px',
                fontSize: '12px'
              }}>
                {upcomingRaces.reduce((sum, r) => sum + r.entries.length, 0)}
              </span>
            </button>
            <button
              onClick={() => setRaceFilter('completed')}
              style={{
                padding: '12px 24px',
                background: raceFilter === 'completed' ? 'var(--primary)' : 'white',
                color: raceFilter === 'completed' ? 'white' : 'var(--text-secondary)',
                border: '1px solid var(--border)',
                borderLeft: 'none',
                borderRadius: '0 8px 8px 0',
                cursor: 'pointer',
                fontWeight: raceFilter === 'completed' ? '600' : '400',
                display: 'flex',
                alignItems: 'center',
                gap: '8px'
              }}
            >
              <Trophy size={16} />
              Avslutade
              <span style={{
                background: raceFilter === 'completed' ? 'rgba(255,255,255,0.2)' : 'var(--background)',
                padding: '2px 8px',
                borderRadius: '10px',
                fontSize: '12px'
              }}>
                {completedRaces.reduce((sum, r) => sum + r.entries.length, 0)}
              </span>
            </button>
          </div>

          {/* Race Calendar */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
            {filteredRaces.length === 0 ? (
              <div className="card" style={{ padding: '60px 40px', textAlign: 'center' }}>
                <Trophy size={48} style={{ marginBottom: '16px', opacity: 0.3, color: 'var(--text-muted)' }} />
                <h3 style={{ color: 'var(--text-muted)', marginBottom: '8px' }}>Inga {raceFilter === 'upcoming' ? 'kommande' : 'avslutade'} starter</h3>
              </div>
            ) : (
              filteredRaces.map(race => (
                <div
                  key={race.id}
                  className="card"
                  style={{ overflow: 'hidden' }}
                >
                  {/* Race Header */}
                  <div
                    style={{
                      padding: '16px 20px',
                      background: isToday(race.date) ? 'rgba(79, 124, 255, 0.08)' : 'var(--background)',
                      borderBottom: '1px solid var(--border)',
                      display: 'flex',
                      justifyContent: 'space-between',
                      alignItems: 'center',
                      cursor: 'pointer'
                    }}
                    onClick={() => toggleRaceExpanded(race.id)}
                  >
                    <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
                      <div style={{
                        width: '56px',
                        height: '56px',
                        borderRadius: '12px',
                        background: isToday(race.date) ? 'var(--primary)' : 'white',
                        border: isToday(race.date) ? 'none' : '1px solid var(--border)',
                        display: 'flex',
                        flexDirection: 'column',
                        alignItems: 'center',
                        justifyContent: 'center',
                        color: isToday(race.date) ? 'white' : 'var(--text-primary)'
                      }}>
                        <div style={{ fontSize: '18px', fontWeight: '700', lineHeight: 1 }}>
                          {race.date.getDate()}
                        </div>
                        <div style={{ fontSize: '10px', textTransform: 'uppercase' }}>
                          {race.date.toLocaleDateString('sv-SE', { month: 'short' })}
                        </div>
                      </div>
                      <div>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                          <h3 style={{ fontSize: '18px', fontWeight: '600' }}>{race.track}</h3>
                          <span style={{
                            fontSize: '12px',
                            background: race.raceType === 'V75' ? '#EF4444' :
                                       race.raceType === 'V86' ? '#8B5CF6' :
                                       race.raceType === 'V64' ? '#F59E0B' : 'var(--text-muted)',
                            color: 'white',
                            padding: '2px 8px',
                            borderRadius: '4px',
                            fontWeight: '600'
                          }}>
                            {race.raceType}
                          </span>
                          {isToday(race.date) && (
                            <span style={{
                              fontSize: '11px',
                              background: 'var(--primary)',
                              color: 'white',
                              padding: '2px 8px',
                              borderRadius: '4px'
                            }}>
                              IDAG
                            </span>
                          )}
                        </div>
                        <div style={{ fontSize: '13px', color: 'var(--text-muted)', marginTop: '4px', display: 'flex', alignItems: 'center', gap: '12px' }}>
                          <span>{race.date.toLocaleDateString('sv-SE', { weekday: 'long' })}</span>
                          <span>•</span>
                          <span>{race.entries.length} {race.entries.length === 1 ? 'start' : 'starter'}</span>
                          {raceFilter === 'upcoming' && (
                            <>
                              <span>•</span>
                              <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                                <Truck size={12} />
                                Avfärd {race.departureTime}
                              </span>
                            </>
                          )}
                          {raceFilter === 'completed' && (
                            <>
                              <span>•</span>
                              <span style={{ color: 'var(--success)', fontWeight: '500' }}>
                                {formatCurrency(race.entries.reduce((sum, e) => sum + (e.earnings || 0), 0))}
                              </span>
                            </>
                          )}
                        </div>
                      </div>
                    </div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                      {expandedRaces.includes(race.id) ? (
                        <ChevronUp size={20} style={{ color: 'var(--text-muted)' }} />
                      ) : (
                        <ChevronDown size={20} style={{ color: 'var(--text-muted)' }} />
                      )}
                    </div>
                  </div>

                  {/* Expanded Race Details */}
                  {expandedRaces.includes(race.id) && (
                    <div>
                      {/* Transport & Logistics for upcoming */}
                      {raceFilter === 'upcoming' && (
                        <div style={{
                          padding: '16px 20px',
                          background: 'white',
                          borderBottom: '1px solid var(--border)',
                          display: 'flex',
                          gap: '24px',
                          flexWrap: 'wrap'
                        }}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                            <Truck size={16} style={{ color: 'var(--text-muted)' }} />
                            <span style={{ fontSize: '13px', color: 'var(--text-muted)' }}>Transport:</span>
                            <select
                              value={race.transportDriver}
                              onChange={(e) => updateRace(race.id, 'transportDriver', e.target.value)}
                              style={{
                                padding: '4px 8px',
                                borderRadius: '6px',
                                border: '1px solid var(--border)',
                                fontSize: '13px'
                              }}
                              onClick={(e) => e.stopPropagation()}
                            >
                              {transportDrivers.map(d => (
                                <option key={d.id} value={d.name}>{d.name}</option>
                              ))}
                            </select>
                          </div>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                            <Clock size={16} style={{ color: 'var(--text-muted)' }} />
                            <span style={{ fontSize: '13px', color: 'var(--text-muted)' }}>Avfärd:</span>
                            <input
                              type="time"
                              value={race.departureTime}
                              onChange={(e) => updateRace(race.id, 'departureTime', e.target.value)}
                              style={{
                                padding: '4px 8px',
                                borderRadius: '6px',
                                border: '1px solid var(--border)',
                                fontSize: '13px'
                              }}
                              onClick={(e) => e.stopPropagation()}
                            />
                          </div>
                        </div>
                      )}

                      {/* Race Entries Table */}
                      <table style={{ width: '100%' }}>
                        <thead>
                          <tr style={{ background: 'white' }}>
                            <th style={{ padding: '12px 20px', textAlign: 'left', fontSize: '12px', fontWeight: '600', color: 'var(--text-muted)' }}>Lopp</th>
                            <th style={{ padding: '12px 20px', textAlign: 'left', fontSize: '12px', fontWeight: '600', color: 'var(--text-muted)' }}>Häst</th>
                            <th style={{ padding: '12px 20px', textAlign: 'left', fontSize: '12px', fontWeight: '600', color: 'var(--text-muted)' }}>Startnr</th>
                            <th style={{ padding: '12px 20px', textAlign: 'left', fontSize: '12px', fontWeight: '600', color: 'var(--text-muted)' }}>Distans</th>
                            <th style={{ padding: '12px 20px', textAlign: 'left', fontSize: '12px', fontWeight: '600', color: 'var(--text-muted)' }}>Kusk</th>
                            <th style={{ padding: '12px 20px', textAlign: 'left', fontSize: '12px', fontWeight: '600', color: 'var(--text-muted)' }}>Skötare</th>
                            {raceFilter === 'completed' && (
                              <>
                                <th style={{ padding: '12px 20px', textAlign: 'center', fontSize: '12px', fontWeight: '600', color: 'var(--text-muted)' }}>Placering</th>
                                <th style={{ padding: '12px 20px', textAlign: 'right', fontSize: '12px', fontWeight: '600', color: 'var(--text-muted)' }}>Intjänat</th>
                              </>
                            )}
                            {raceFilter === 'upcoming' && (
                              <th style={{ padding: '12px 20px', textAlign: 'center', fontSize: '12px', fontWeight: '600', color: 'var(--text-muted)' }}>Status</th>
                            )}
                          </tr>
                        </thead>
                        <tbody>
                          {race.entries
                            .sort((a, b) => a.race - b.race)
                            .map((entry, idx) => (
                            <tr
                              key={idx}
                              style={{
                                borderTop: '1px solid var(--border-light)'
                              }}
                            >
                              <td style={{ padding: '12px 20px' }}>
                                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                                  <span style={{
                                    width: '32px',
                                    height: '32px',
                                    borderRadius: '8px',
                                    background: 'var(--primary)10',
                                    color: 'var(--primary)',
                                    display: 'inline-flex',
                                    alignItems: 'center',
                                    justifyContent: 'center',
                                    fontWeight: '600'
                                  }}>
                                    {entry.race}
                                  </span>
                                  {entry.poolRace && (
                                    <span style={{
                                      fontSize: '11px',
                                      background: race.raceType === 'V75' ? '#EF444415' :
                                                 race.raceType === 'V86' ? '#8B5CF615' :
                                                 race.raceType === 'V64' ? '#F59E0B15' : 'var(--background)',
                                      color: race.raceType === 'V75' ? '#EF4444' :
                                             race.raceType === 'V86' ? '#8B5CF6' :
                                             race.raceType === 'V64' ? '#F59E0B' : 'var(--text-muted)',
                                      padding: '2px 6px',
                                      borderRadius: '4px',
                                      fontWeight: '600'
                                    }}>
                                      {entry.poolRace}
                                    </span>
                                  )}
                                </div>
                              </td>
                              <td style={{ padding: '12px 20px' }}>
                                <div style={{ fontWeight: '600' }}>{entry.horse}</div>
                              </td>
                              <td style={{ padding: '12px 20px' }}>
                                <span style={{
                                  width: '28px',
                                  height: '28px',
                                  borderRadius: '50%',
                                  background: 'var(--background)',
                                  display: 'inline-flex',
                                  alignItems: 'center',
                                  justifyContent: 'center',
                                  fontWeight: '600',
                                  fontSize: '13px'
                                }}>
                                  {entry.startNumber}
                                </span>
                              </td>
                              <td style={{ padding: '12px 20px', color: 'var(--text-secondary)' }}>
                                {entry.distance}
                              </td>
                              <td style={{ padding: '12px 20px', color: 'var(--text-secondary)' }}>
                                {entry.driver}
                              </td>
                              <td style={{ padding: '12px 20px' }}>
                                {raceFilter === 'upcoming' ? (
                                  <select
                                    value={entry.groom}
                                    onChange={(e) => updateRaceEntry(race.id, idx, 'groom', e.target.value)}
                                    style={{
                                      padding: '6px 10px',
                                      borderRadius: '6px',
                                      border: '1px solid var(--border)',
                                      fontSize: '13px',
                                      background: 'white'
                                    }}
                                    onClick={(e) => e.stopPropagation()}
                                  >
                                    <option value="">Välj skötare</option>
                                    {grooms.map(g => (
                                      <option key={g.id} value={g.name}>{g.name}</option>
                                    ))}
                                  </select>
                                ) : (
                                  <span style={{ color: 'var(--text-secondary)' }}>{entry.groom}</span>
                                )}
                              </td>
                              {raceFilter === 'completed' && (
                                <>
                                  <td style={{ padding: '12px 20px', textAlign: 'center' }}>
                                    <span style={{
                                      display: 'inline-flex',
                                      alignItems: 'center',
                                      justifyContent: 'center',
                                      width: '32px',
                                      height: '32px',
                                      borderRadius: '50%',
                                      background: entry.placement <= 3 ? `${getPlacementColor(entry.placement)}20` : 'var(--background)',
                                      color: getPlacementColor(entry.placement),
                                      fontWeight: '700',
                                      fontSize: '14px'
                                    }}>
                                      {entry.placement || '-'}
                                    </span>
                                  </td>
                                  <td style={{ padding: '12px 20px', textAlign: 'right' }}>
                                    <span style={{
                                      fontWeight: '600',
                                      color: entry.earnings > 50000 ? 'var(--success)' : 'var(--text-primary)'
                                    }}>
                                      {formatCurrency(entry.earnings || 0)}
                                    </span>
                                  </td>
                                </>
                              )}
                              {raceFilter === 'upcoming' && (
                                <td style={{ padding: '12px 20px', textAlign: 'center' }}>
                                  {entry.status === 'confirmed' ? (
                                    <span style={{
                                      display: 'inline-flex',
                                      alignItems: 'center',
                                      gap: '4px',
                                      fontSize: '12px',
                                      color: 'var(--success)',
                                      background: 'var(--success-light)',
                                      padding: '4px 10px',
                                      borderRadius: '4px'
                                    }}>
                                      <Check size={12} />
                                      Bekräftad
                                    </span>
                                  ) : (
                                    <span style={{
                                      display: 'inline-flex',
                                      alignItems: 'center',
                                      gap: '4px',
                                      fontSize: '12px',
                                      color: 'var(--warning)',
                                      background: 'var(--warning-light)',
                                      padding: '4px 10px',
                                      borderRadius: '4px'
                                    }}>
                                      <Clock size={12} />
                                      Anmäld
                                    </span>
                                  )}
                                </td>
                              )}
                            </tr>
                          ))}
                        </tbody>
                      </table>

                      {/* Push to App Button */}
                      {raceFilter === 'upcoming' && (
                        <div style={{
                          padding: '16px 20px',
                          borderTop: '1px solid var(--border)',
                          display: 'flex',
                          justifyContent: 'flex-end'
                        }}>
                          <button className="btn btn-secondary" style={{ padding: '8px 16px' }}>
                            <Send size={14} />
                            Uppdatera i appen
                          </button>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              ))
            )}
          </div>
        </>
      )}

      {/* Event Detail Modal */}
      {selectedEvent && (
        <div style={{
          position: 'fixed',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          background: 'rgba(0,0,0,0.5)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          zIndex: 1000
        }} onClick={() => setSelectedEvent(null)}>
          <div style={{
            background: 'white',
            borderRadius: '16px',
            width: '100%',
            maxWidth: '650px',
            margin: '20px',
            maxHeight: '90vh',
            overflow: 'hidden',
            display: 'flex',
            flexDirection: 'column'
          }} onClick={e => e.stopPropagation()}>
            {/* Modal Header */}
            <div style={{
              padding: '20px 24px',
              borderBottom: '1px solid var(--border)',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'flex-start'
            }}>
              <div>
                <div style={{
                  display: 'inline-flex',
                  alignItems: 'center',
                  gap: '8px',
                  background: `${getEventTypeInfo(selectedEvent.type).color}15`,
                  color: getEventTypeInfo(selectedEvent.type).color,
                  padding: '4px 12px',
                  borderRadius: '100px',
                  fontSize: '12px',
                  fontWeight: '600',
                  marginBottom: '8px'
                }}>
                  {(() => {
                    const TypeIcon = getEventTypeInfo(selectedEvent.type).icon;
                    return <TypeIcon size={14} />;
                  })()}
                  {getEventTypeInfo(selectedEvent.type).label}
                  {selectedEvent.isAutoGenerated && ' • Från anmälan'}
                </div>
                <h2>{selectedEvent.title}</h2>
              </div>
              <button
                onClick={() => setSelectedEvent(null)}
                style={{
                  background: 'none',
                  border: 'none',
                  cursor: 'pointer',
                  padding: '8px'
                }}
              >
                <X size={20} style={{ color: 'var(--text-muted)' }} />
              </button>
            </div>

            {/* Modal Body */}
            <div style={{ padding: '24px', overflowY: 'auto', flex: 1 }}>
              {/* Event Details */}
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '16px', marginBottom: '24px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  <div style={{
                    width: '40px',
                    height: '40px',
                    borderRadius: '10px',
                    background: 'var(--background)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center'
                  }}>
                    <Calendar size={20} style={{ color: 'var(--text-muted)' }} />
                  </div>
                  <div>
                    <div style={{ fontSize: '12px', color: 'var(--text-muted)' }}>Datum</div>
                    <div style={{ fontWeight: '500' }}>{formatDateLong(selectedEvent.date)}</div>
                  </div>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  <div style={{
                    width: '40px',
                    height: '40px',
                    borderRadius: '10px',
                    background: 'var(--background)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center'
                  }}>
                    <Clock size={20} style={{ color: 'var(--text-muted)' }} />
                  </div>
                  <div>
                    <div style={{ fontSize: '12px', color: 'var(--text-muted)' }}>Tid</div>
                    <div style={{ fontWeight: '500' }}>{selectedEvent.time}</div>
                  </div>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  <div style={{
                    width: '40px',
                    height: '40px',
                    borderRadius: '10px',
                    background: 'var(--background)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center'
                  }}>
                    <MapPin size={20} style={{ color: 'var(--text-muted)' }} />
                  </div>
                  <div>
                    <div style={{ fontSize: '12px', color: 'var(--text-muted)' }}>Plats</div>
                    <div style={{ fontWeight: '500' }}>{selectedEvent.location}</div>
                  </div>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  <div style={{
                    width: '40px',
                    height: '40px',
                    borderRadius: '10px',
                    background: 'var(--background)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center'
                  }}>
                    <Users size={20} style={{ color: 'var(--text-muted)' }} />
                  </div>
                  <div>
                    <div style={{ fontSize: '12px', color: 'var(--text-muted)' }}>Anmälda</div>
                    <div style={{ fontWeight: '500' }}>
                      {selectedEvent.attendees}
                      {selectedEvent.maxAttendees && ` / ${selectedEvent.maxAttendees}`}
                    </div>
                  </div>
                </div>
              </div>

              {/* Description */}
              <div style={{ marginBottom: '24px' }}>
                <h4 style={{ fontSize: '14px', color: 'var(--text-muted)', marginBottom: '8px' }}>
                  Beskrivning (visas i appen)
                </h4>
                <div style={{
                  fontSize: '14px',
                  lineHeight: '1.6',
                  background: 'var(--background)',
                  padding: '16px',
                  borderRadius: '8px',
                  whiteSpace: 'pre-wrap'
                }}>
                  {selectedEvent.description}
                </div>
              </div>

              {/* Trainer Notes for race days */}
              {selectedEvent.type === 'race-day' && (
                <div style={{ marginBottom: '24px' }}>
                  <h4 style={{
                    fontSize: '14px',
                    color: 'var(--text-muted)',
                    marginBottom: '8px',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '8px'
                  }}>
                    <MessageSquare size={14} />
                    Exklusiv info till ägare
                  </h4>
                  {selectedEvent.trainerNotes ? (
                    <div style={{
                      background: 'linear-gradient(135deg, #4F7CFF08 0%, #8B5CF608 100%)',
                      border: '1px solid #4F7CFF30',
                      padding: '16px',
                      borderRadius: '12px'
                    }}>
                      <div style={{ fontSize: '14px', lineHeight: '1.6', margin: 0, whiteSpace: 'pre-wrap' }}>
                        {selectedEvent.trainerNotes}
                      </div>
                      <div style={{ marginTop: '12px', display: 'flex', justifyContent: 'flex-end' }}>
                        <button className="btn btn-secondary" style={{ padding: '6px 12px', fontSize: '13px' }}>
                          <Edit3 size={14} />
                          Redigera
                        </button>
                      </div>
                    </div>
                  ) : (
                    <div style={{
                      background: 'var(--background)',
                      border: '2px dashed var(--border)',
                      padding: '24px',
                      borderRadius: '12px',
                      textAlign: 'center'
                    }}>
                      <MessageSquare size={24} style={{ color: 'var(--text-muted)', marginBottom: '8px' }} />
                      <p style={{ color: 'var(--text-muted)', fontSize: '14px', margin: '0 0 12px 0' }}>
                        Lägg till exklusiv information för hästägarna
                      </p>
                      <button className="btn btn-primary" style={{ padding: '8px 16px' }}>
                        <Plus size={14} />
                        Lägg till info
                      </button>
                    </div>
                  )}
                </div>
              )}

              {/* Related Horses */}
              {selectedEvent.relatedHorses.length > 0 && (
                <div style={{ marginBottom: '24px' }}>
                  <h4 style={{ fontSize: '14px', color: 'var(--text-muted)', marginBottom: '8px' }}>Stallets hästar</h4>
                  <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
                    {selectedEvent.relatedHorses.map(horse => (
                      <span
                        key={horse}
                        style={{
                          fontSize: '13px',
                          background: 'var(--primary)10',
                          color: 'var(--primary)',
                          padding: '8px 14px',
                          borderRadius: '8px',
                          fontWeight: '500'
                        }}
                      >
                        {horse}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {/* Publish Status */}
              <div style={{
                padding: '16px',
                background: selectedEvent.publishedToApp ? 'var(--success-light)' : 'var(--background)',
                borderRadius: '12px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between'
              }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  {selectedEvent.publishedToApp ? (
                    <Eye size={20} style={{ color: 'var(--success)' }} />
                  ) : (
                    <EyeOff size={20} style={{ color: 'var(--text-muted)' }} />
                  )}
                  <div>
                    <div style={{ fontWeight: '500' }}>
                      {selectedEvent.publishedToApp ? 'Publicerat i appen' : 'Ej publicerat'}
                    </div>
                    <div style={{ fontSize: '12px', color: 'var(--text-muted)' }}>
                      {selectedEvent.publishedToApp
                        ? 'Synligt för alla hästägare'
                        : 'Endast synligt för dig'
                      }
                    </div>
                  </div>
                </div>
                <button
                  className={`btn ${selectedEvent.publishedToApp ? 'btn-secondary' : 'btn-primary'}`}
                  onClick={() => {
                    togglePublishEvent(selectedEvent.id);
                    setSelectedEvent(prev => ({ ...prev, publishedToApp: !prev.publishedToApp }));
                  }}
                >
                  {selectedEvent.publishedToApp ? 'Avpublicera' : 'Publicera'}
                </button>
              </div>
            </div>

            {/* Modal Footer */}
            <div style={{
              padding: '16px 24px',
              borderTop: '1px solid var(--border)',
              display: 'flex',
              gap: '12px',
              justifyContent: 'space-between'
            }}>
              {!selectedEvent.isAutoGenerated && (
                <button
                  className="btn btn-secondary"
                  style={{ color: 'var(--danger)' }}
                  onClick={() => deleteEvent(selectedEvent.id)}
                >
                  <Trash2 size={16} />
                  Ta bort
                </button>
              )}
              {selectedEvent.isAutoGenerated && <div />}
              <div style={{ display: 'flex', gap: '12px' }}>
                <button className="btn btn-secondary" onClick={() => setSelectedEvent(null)}>
                  Stäng
                </button>
                <button className="btn btn-primary">
                  <Edit3 size={16} />
                  Redigera
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Add Event Modal */}
      {showAddEventModal && (
        <div style={{
          position: 'fixed',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          background: 'rgba(0,0,0,0.5)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          zIndex: 1000
        }} onClick={() => setShowAddEventModal(false)}>
          <div style={{
            background: 'white',
            borderRadius: '16px',
            width: '100%',
            maxWidth: '600px',
            margin: '20px',
            maxHeight: '90vh',
            overflow: 'hidden',
            display: 'flex',
            flexDirection: 'column'
          }} onClick={e => e.stopPropagation()}>
            {/* Modal Header */}
            <div style={{
              padding: '20px 24px',
              borderBottom: '1px solid var(--border)',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center'
            }}>
              <h2>Skapa nytt event</h2>
              <button
                onClick={() => setShowAddEventModal(false)}
                style={{
                  background: 'none',
                  border: 'none',
                  cursor: 'pointer',
                  padding: '8px'
                }}
              >
                <X size={20} style={{ color: 'var(--text-muted)' }} />
              </button>
            </div>

            {/* Modal Body */}
            <div style={{ padding: '24px', overflowY: 'auto', flex: 1 }}>
              {/* Info box */}
              <div style={{
                background: 'var(--background)',
                padding: '12px 16px',
                borderRadius: '8px',
                marginBottom: '20px',
                fontSize: '13px',
                color: 'var(--text-secondary)',
                display: 'flex',
                alignItems: 'flex-start',
                gap: '10px'
              }}>
                <AlertCircle size={16} style={{ marginTop: '2px', flexShrink: 0 }} />
                <span>
                  Tävlingsdagar skapas automatiskt när hästar anmäls. Använd detta formulär för träffar, fester och andra event.
                </span>
              </div>

              {/* Event Type */}
              <div style={{ marginBottom: '24px' }}>
                <label style={{ fontSize: '14px', fontWeight: '600', display: 'block', marginBottom: '12px' }}>
                  Typ av event
                </label>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
                  {eventTypes.filter(t => t.id !== 'race-day').map(type => {
                    const TypeIcon = type.icon;
                    return (
                      <div
                        key={type.id}
                        onClick={() => setNewEvent(prev => ({ ...prev, type: type.id }))}
                        style={{
                          padding: '12px 16px',
                          borderRadius: '8px',
                          border: newEvent.type === type.id ? `2px solid ${type.color}` : '2px solid var(--border)',
                          background: newEvent.type === type.id ? `${type.color}10` : 'white',
                          cursor: 'pointer',
                          display: 'flex',
                          alignItems: 'center',
                          gap: '8px'
                        }}
                      >
                        <TypeIcon size={18} style={{ color: type.color }} />
                        <span style={{
                          fontWeight: '500',
                          color: newEvent.type === type.id ? type.color : 'var(--text-primary)'
                        }}>
                          {type.label}
                        </span>
                      </div>
                    );
                  })}
                </div>
              </div>

              {/* Title */}
              <div style={{ marginBottom: '16px' }}>
                <label style={{ fontSize: '12px', color: 'var(--text-muted)', display: 'block', marginBottom: '6px' }}>
                  Titel
                </label>
                <input
                  type="text"
                  value={newEvent.title}
                  onChange={(e) => setNewEvent(prev => ({ ...prev, title: e.target.value }))}
                  placeholder="T.ex. Hästägarträff på Solvalla"
                  style={{
                    width: '100%',
                    padding: '10px 12px',
                    borderRadius: '8px',
                    border: '1px solid var(--border)',
                    fontSize: '14px'
                  }}
                />
              </div>

              {/* Date and Time */}
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', marginBottom: '16px' }}>
                <div>
                  <label style={{ fontSize: '12px', color: 'var(--text-muted)', display: 'block', marginBottom: '6px' }}>
                    Datum
                  </label>
                  <input
                    type="date"
                    value={newEvent.date}
                    onChange={(e) => setNewEvent(prev => ({ ...prev, date: e.target.value }))}
                    style={{
                      width: '100%',
                      padding: '10px 12px',
                      borderRadius: '8px',
                      border: '1px solid var(--border)',
                      fontSize: '14px'
                    }}
                  />
                </div>
                <div>
                  <label style={{ fontSize: '12px', color: 'var(--text-muted)', display: 'block', marginBottom: '6px' }}>
                    Tid
                  </label>
                  <input
                    type="time"
                    value={newEvent.time}
                    onChange={(e) => setNewEvent(prev => ({ ...prev, time: e.target.value }))}
                    style={{
                      width: '100%',
                      padding: '10px 12px',
                      borderRadius: '8px',
                      border: '1px solid var(--border)',
                      fontSize: '14px'
                    }}
                  />
                </div>
              </div>

              {/* Location */}
              <div style={{ marginBottom: '16px' }}>
                <label style={{ fontSize: '12px', color: 'var(--text-muted)', display: 'block', marginBottom: '6px' }}>
                  Plats
                </label>
                <input
                  type="text"
                  value={newEvent.location}
                  onChange={(e) => setNewEvent(prev => ({ ...prev, location: e.target.value }))}
                  placeholder="T.ex. Solvalla, Restaurang Hästskon"
                  style={{
                    width: '100%',
                    padding: '10px 12px',
                    borderRadius: '8px',
                    border: '1px solid var(--border)',
                    fontSize: '14px'
                  }}
                />
              </div>

              {/* Description */}
              <div style={{ marginBottom: '16px' }}>
                <label style={{ fontSize: '12px', color: 'var(--text-muted)', display: 'block', marginBottom: '6px' }}>
                  Beskrivning (visas i appen)
                </label>
                <textarea
                  value={newEvent.description}
                  onChange={(e) => setNewEvent(prev => ({ ...prev, description: e.target.value }))}
                  placeholder="Beskriv eventet för hästägarna..."
                  style={{
                    width: '100%',
                    padding: '12px',
                    borderRadius: '8px',
                    border: '1px solid var(--border)',
                    fontSize: '14px',
                    minHeight: '100px',
                    resize: 'vertical'
                  }}
                />
              </div>

              {/* Max Attendees and RSVP Deadline */}
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', marginBottom: '16px' }}>
                <div>
                  <label style={{ fontSize: '12px', color: 'var(--text-muted)', display: 'block', marginBottom: '6px' }}>
                    Max antal deltagare (valfritt)
                  </label>
                  <input
                    type="number"
                    value={newEvent.maxAttendees}
                    onChange={(e) => setNewEvent(prev => ({ ...prev, maxAttendees: e.target.value }))}
                    placeholder="40"
                    style={{
                      width: '100%',
                      padding: '10px 12px',
                      borderRadius: '8px',
                      border: '1px solid var(--border)',
                      fontSize: '14px'
                    }}
                  />
                </div>
                <div>
                  <label style={{ fontSize: '12px', color: 'var(--text-muted)', display: 'block', marginBottom: '6px' }}>
                    Sista anmälningsdag (valfritt)
                  </label>
                  <input
                    type="date"
                    value={newEvent.rsvpDeadline}
                    onChange={(e) => setNewEvent(prev => ({ ...prev, rsvpDeadline: e.target.value }))}
                    style={{
                      width: '100%',
                      padding: '10px 12px',
                      borderRadius: '8px',
                      border: '1px solid var(--border)',
                      fontSize: '14px'
                    }}
                  />
                </div>
              </div>

              {/* Publish Toggle */}
              <label style={{
                display: 'flex',
                alignItems: 'center',
                gap: '12px',
                padding: '16px',
                borderRadius: '12px',
                border: '1px solid var(--border)',
                cursor: 'pointer',
                background: newEvent.publishedToApp ? 'var(--success-light)' : 'white'
              }}>
                <input
                  type="checkbox"
                  checked={newEvent.publishedToApp}
                  onChange={(e) => setNewEvent(prev => ({ ...prev, publishedToApp: e.target.checked }))}
                  style={{ width: '18px', height: '18px' }}
                />
                <div>
                  <div style={{ fontWeight: '500' }}>Publicera direkt i appen</div>
                  <div style={{ fontSize: '12px', color: 'var(--text-muted)' }}>
                    Eventet blir synligt för alla hästägare
                  </div>
                </div>
                <Eye size={18} style={{ marginLeft: 'auto', color: newEvent.publishedToApp ? 'var(--success)' : 'var(--text-muted)' }} />
              </label>
            </div>

            {/* Modal Footer */}
            <div style={{
              padding: '16px 24px',
              borderTop: '1px solid var(--border)',
              display: 'flex',
              gap: '12px',
              justifyContent: 'flex-end'
            }}>
              <button
                className="btn btn-secondary"
                onClick={() => setShowAddEventModal(false)}
              >
                Avbryt
              </button>
              <button
                className="btn btn-primary"
                onClick={handleCreateEvent}
                disabled={!newEvent.title || !newEvent.date || !newEvent.time || !newEvent.location}
                style={{
                  opacity: (!newEvent.title || !newEvent.date || !newEvent.time || !newEvent.location) ? 0.5 : 1
                }}
              >
                <Plus size={16} />
                Skapa event
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
